CREATE TABLE eps (
  eps_id SERIAL PRIMARY KEY,
  eps_nombre VARCHAR(150) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP
);

INSERT INTO eps (eps_nombre) VALUES
('Coosalud EPS-S'),
('Nueva EPS'),
('Mutual Ser'),
('Salud Mía'),
('Aliansalud EPS'),
('Salud Total EPS S.A.'),
('EPS Sanitas'),
('EPS Sura'),
('Famisanar'),
('Servicio Occidental de Salud (SOS)'),
('Comfenalco Valle'),
('Compensar EPS'),
('Empresas Públicas de Medellín (EPM)'),
('Fondo de Pasivo Social de Ferrocarriles Nacionales de Colombia'),
('Cajacopi Atlántico'),
('Capresoca'),
('Comfachocó'),
('Comfaoriente'),
('EPS Familiar de Colombia'),
('Asmet Salud'),
('Emssanar E.S.S.'),
('Capital Salud EPS-S'),
('Savia Salud EPS'),
('Dusakawi EPSI'),
('Asociación Indígena del Cauca EPSI'),
('Anas Wayuu EPSI'),
('Mallamas EPSI'),
('Pijaos Salud EPSI');
