BEGIN;
ALTER TABLE public.alimentacion ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read alimentacion" ON public.alimentacion FOR SELECT TO public USING (true);
CREATE POLICY anon_insert_alimentacion ON public.alimentacion FOR INSERT TO anon, authenticated USING (TRUE) WITH CHECK (true);
CREATE POLICY anon_select_alimentacion ON public.alimentacion FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY anon_update_alimentacion ON public.alimentacion FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY sel_anon ON public.alimentacion FOR SELECT TO anon USING (true);
ALTER TABLE public.autorizados ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon can delete autorizados by id" ON public.autorizados FOR DELETE TO anon USING (true);
CREATE POLICY "anon can insert autorizados with cedula 6-20" ON public.autorizados FOR INSERT TO anon USING (TRUE) WITH CHECK (((num_cedula)::text ~ '^[0-9]{6,20}$'::text));
CREATE POLICY "anon can select autorizados" ON public.autorizados FOR SELECT TO anon USING (true);
CREATE POLICY "anon can update autorizados with cedula 6-20" ON public.autorizados FOR UPDATE TO anon USING (true) WITH CHECK (((num_cedula)::text ~ '^[0-9]{6,20}$'::text));
CREATE POLICY "anon delete autorizados" ON public.autorizados FOR DELETE TO anon USING (true);
CREATE POLICY "anon insert autorizados cedula 6-10" ON public.autorizados FOR INSERT TO anon USING (TRUE) WITH CHECK (((num_cedula)::text ~ '^[0-9]{6,10}$'::text));
CREATE POLICY "anon insert autorizados cedula 6-20" ON public.autorizados FOR INSERT TO anon USING (TRUE) WITH CHECK (((num_cedula)::text ~ '^[0-9]{6,20}$'::text));
CREATE POLICY "anon select autorizados" ON public.autorizados FOR SELECT TO anon USING (true);
CREATE POLICY "anon update autorizados cedula 6-10" ON public.autorizados FOR UPDATE TO anon USING (true) WITH CHECK (((num_cedula)::text ~ '^[0-9]{6,10}$'::text));
CREATE POLICY "anon update autorizados cedula 6-20" ON public.autorizados FOR UPDATE TO anon USING (true) WITH CHECK (((num_cedula)::text ~ '^[0-9]{6,20}$'::text));
CREATE POLICY anon_read_autorizados ON public.autorizados FOR SELECT TO anon USING (true);
CREATE POLICY auth_read_autorizados ON public.autorizados FOR SELECT TO authenticated USING (true);
ALTER TABLE public.bancos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read bancos" ON public.bancos FOR SELECT TO public USING (true);
CREATE POLICY sel_anon ON public.bancos FOR SELECT TO anon USING (true);
ALTER TABLE public.ciudades ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read ciudades" ON public.ciudades FOR SELECT TO public USING (true);
CREATE POLICY anon_insert_ciudades ON public.ciudades FOR INSERT TO anon, authenticated USING (TRUE) WITH CHECK (true);
CREATE POLICY anon_select_ciudades ON public.ciudades FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY crud_authenticated ON public.ciudades FOR ALL TO authenticated USING (true);
CREATE POLICY sel_anon ON public.ciudades FOR SELECT TO anon USING (true);
ALTER TABLE public.datos_bancarios ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon can insert datos_bancarios" ON public.datos_bancarios FOR INSERT TO public USING (TRUE) WITH CHECK (true);
CREATE POLICY "anon can select datos_bancarios" ON public.datos_bancarios FOR SELECT TO public USING (true);
ALTER TABLE public.epss ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read epss" ON public.epss FOR SELECT TO public USING (true);
CREATE POLICY anon_insert_epss ON public.epss FOR INSERT TO anon, authenticated USING (TRUE) WITH CHECK (true);
CREATE POLICY anon_select_epss ON public.epss FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY sel_anon ON public.epss FOR SELECT TO anon USING (true);
ALTER TABLE public.generos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read generos" ON public.generos FOR SELECT TO public USING (true);
CREATE POLICY sel_anon ON public.generos FOR SELECT TO anon USING (true);
ALTER TABLE public.perfilamiento ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read perfilamiento" ON public.perfilamiento FOR SELECT TO public USING (true);
CREATE POLICY sel_anon ON public.perfilamiento FOR SELECT TO anon USING (true);
ALTER TABLE public.personal ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon can insert personal" ON public.personal FOR INSERT TO public USING (TRUE) WITH CHECK (true);
CREATE POLICY "anon can select personal" ON public.personal FOR SELECT TO public USING (true);
CREATE POLICY personal_insert_anon_autorizados ON public.personal FOR INSERT TO anon USING (TRUE) WITH CHECK ((EXISTS ( SELECT 1
   FROM autorizados a
  WHERE ((a.num_cedula)::text = (personal.per_num_doc)::text))));
ALTER TABLE public.status_personal ENABLE ROW LEVEL SECURITY;
CREATE POLICY anon_insert_status ON public.status_personal FOR INSERT TO anon USING (TRUE) WITH CHECK (true);
CREATE POLICY anon_select_status ON public.status_personal FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY sel_anon ON public.status_personal FOR SELECT TO anon USING (true);
COMMIT;